variable "my_ip" {}
variable "env" {}
variable "department" {}
variable "aws_region" {}
variable "vpc_id" {}

variable "subnets" {
  type = "list"
}

variable "snowplow_service_user" {}
variable "snowplow_service_group" {}
variable "snowplow_home" {}
variable "snowplow_system_tag" {}
variable "snowplow_ec2_keypair" {}
variable "snowplow_ec2_keypair_path" {}
variable "snowplow_lb_port" {}
variable "snowplow_lb_protocol" {}
variable "snowplow_lb_target_group_protocol" {}
variable "snowplow_lb_health_path" {}
variable "snowplow_lb_healthy_threshold" {}
variable "snowplow_lb_unhealthy_threshold" {}
variable "snowplow_lb_health_timeout" {}
variable "snowplow_lb_health_interval" {}
variable "snowplow_collector_ami_id" {}
variable "snowplow_collector_instance_class" {}
variable "snowplow_collector_root_block_size_gigs" {}
variable "snowplow_collector_node_count" {}
variable "snowplow_collector_ingress_port" {}
variable "snowplow_enricher_ami_id" {}
variable "snowplow_enricher_instance_class" {}
variable "snowplow_enricher_root_block_size_gigs" {}
variable "snowplow_enricher_node_count" {}
variable "snowplow_collector_version" {}
variable "snowplow_collector_buffer_byte_limit" {}
variable "snowplow_collector_buffer_record_limit" {}
variable "snowplow_collector_buffer_time_limit" {}
variable "snowplow_collector_good_stream" {}
variable "snowplow_collector_good_shard_count" {}
variable "snowplow_collector_good_retention_hours" {}
variable "snowplow_collector_bad_stream" {}
variable "snowplow_collector_bad_shard_count" {}
variable "snowplow_collector_bad_retention_hours" {}
variable "snowplow_enricher_version" {}
variable "snowplow_enricher_buffer_byte_limit" {}
variable "snowplow_enricher_buffer_record_limit" {}
variable "snowplow_enricher_buffer_time_limit" {}
variable "snowplow_enricher_good_stream" {}
variable "snowplow_enricher_good_shard_count" {}
variable "snowplow_enricher_good_retention_hours" {}
variable "snowplow_enricher_bad_stream" {}
variable "snowplow_enricher_bad_shard_count" {}
variable "snowplow_enricher_bad_retention_hours" {}
variable "snowplow_enricher_pii_stream" {}
variable "snowplow_enricher_pii_shard_count" {}
variable "snowplow_enricher_pii_retention_hours" {}
variable "snowplow_enricher_checkpoint_table" {}
variable "snowplow_enricher_checkpoint_write_capacity" {}
variable "snowplow_enricher_checkpoint_read_capacity" {}
variable "snowplow_sink_version" {}
variable "snowplow_sink_buffer_byte_limit" {}
variable "snowplow_sink_buffer_record_limit" {}
variable "snowplow_sink_buffer_time_limit" {}
variable "snowplow_sink_good_s3_bucket" {}
variable "snowplow_sink_bad_stream" {}
variable "snowplow_sink_bad_shard_count" {}
variable "snowplow_sink_checkpoint_table" {}
variable "snowplow_sink_checkpoint_write_capacity" {}
variable "snowplow_sink_checkpoint_read_capacity" {}
